//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemKontroliFirmySpedycyjnej.Areas.TransportCompany.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CarId { get; set; }
        public int EmpId { get; set; }
        public string CarName { get; set; }
        public Nullable<int> Millage { get; set; }
        public string VehicleCondition { get; set; }
        public Nullable<bool> CurrentResearch { get; set; }
    }
}
