//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemKontroliFirmySpedycyjnej.Areas.TransportCompany.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSection
    {
        public int SectionId { get; set; }
        public string SectionName { get; set; }
    }
}
