//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemKontroliFirmySpedycyjnej.Areas.TransportCompany.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meetings
    {
        public int MeetId { get; set; }
        public int ContractorId { get; set; }
        public string DateOfMeeting { get; set; }
        public string PlaceOfMeeting { get; set; }
        public string IsOnline { get; set; }
    }
}
