//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemKontroliFirmySpedycyjnej.Areas.TransportCompany.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirmaSpedycyjnaEntities : DbContext
    {
        public FirmaSpedycyjnaEntities()
            : base("name=FirmaSpedycyjnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeSection> EmployeeSection { get; set; }
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<Meetings> Meetings { get; set; }
        public virtual DbSet<TransportCount> TransportCount { get; set; }
    }
}
